stages:
    - build
    - deploy

build-image:
    stage: build
    before_script:
        - buildah login --username "$CI_REGISTRY_USER" --password "$CI_JOB_TOKEN" $CI_REGISTRY
    script:
        - buildah bud --build-arg BASE_IMAGE=arm32v7/debian --file container/Dockerfile --tag "$CI_REGISTRY_IMAGE" .
        - buildah push "$CI_REGISTRY_IMAGE"
    after_script:
        - buildah rmi --all
        - buildah logout $CI_REGISTRY

deploy:
    stage: deploy
    script:
        - chmod og= $ID_RSA
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $USERNAME_PRODUCTION@$HOSTNAME_PRODUCTION "podman login --username $CI_REGISTRY_USER --password $CI_JOB_TOKEN $CI_REGISTRY"
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $USERNAME_PRODUCTION@$HOSTNAME_PRODUCTION "podman pull $CI_REGISTRY_IMAGE"
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $USERNAME_PRODUCTION@$HOSTNAME_PRODUCTION "nohup systemctl --user restart dmarc-record-configurator"
    after_script:
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $USERNAME_PRODUCTION@$HOSTNAME_PRODUCTION "podman logout $CI_REGISTRY"
